package com.sanwaf.core;

public enum Types
{
  INTEGER, INTEGER_DELIMITED, NUMERIC, NUMERIC_DELIMITED, ALPHANUMERIC, ALPHANUMERIC_AND_MORE, STRING, OPEN, CHAR, REGEX, INLINE_REGEX, JAVA, CONSTANT, FORMAT, DEPENDENT_FORMAT, STRICT
}

